# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage
os: osx
osx_image: xcode10.1
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- xcodebuild test -enableCodeCoverage YES -workspace Example/SDMailComposer.xcworkspace -scheme SDMailComposer-Example -sdk iphonesimulator12.1 ONLY_ACTIVE_ARCH=NO
- pod lib lint
